config/routes.rb
Rails.application.routes.draw do

   root "sessions#new"

     resources :projects do
    member do
      patch 'assign_user'
      get 'remove_user'
      patch 'remove_user'
    end
  end



  resources :bugs do
    member do
      patch 'assign'
      put 'assign'
      patch 'change_status'
      put 'change_status'
    end
  end

  resources :project_users

   get '/signup', to: 'users#new'
   post '/signup', to: 'users#create'
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   get '/welcome', to: 'sessions#welcome'
   #get '/authorized', to: 'sessions#page_requires_login'
   delete '/logout', to: 'sessions#destroy'
   #get '/projects', to: 'projects#index'
   #get '/projects/new', to: 'projects#new'
   #get '/projects/create' to: 'projects#new'
   #post '/projects/create' to: 'projects#create'
     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :users
  has_many :bugs,dependent: :destroy
  has_many :project_users,dependent: :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    if current_user.user_type == 'developer'
      @pro=ProjectUser.where(user_id:current_user.id).pluck(:project_id)
      @projects=Project.where(id: @pro)
    else
    @projects = Project.accessible_by(current_ability)
    end
  end

  def show
    @project = Project.find(params[:id])
    @project_id = Project.find(params[:id])
    @bugs=Bug.where(project_id: @project_id)
    @p_user=ProjectUser.where(project_id: @project_id).pluck(:user_id)

    @project_username=User.where(id:@p_user)
     @user=User.all
     @project_user=ProjectUser.where(user_id:@p_user)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'projects#new'
    end
  end
  def edit
     @user = current_user.id
     @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  def remove_user
    @project_id = params[:project_id]
    @user_id = params[:user_id]
    @project_user=ProjectUser.where(project_id:@project_id,user_id:@user_id).pluck(:id)
    if ProjectUser.destroy(@project_user)
      redirect_to '/projects'
    end
  end

  private
    def project_params
      params.require(:project).permit(:user_id, :title, :projectid, :user_assigned)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
    <div >
      <%= form_with model: project do |f| %>
        <h1>Bug Tracking System </h1>
        <%= f.label :user_id %><br>
        <%= f.text_field :user_id, value: current_user.id %><br><br><br>
        <%= f.label :title %><br>
        <%= f.text_field :title  %><br><br><br>
      <%= f.submit "submit", class: "btn btn-primary"%><br><br>

    </div>
    <!--... -->
<% end %>

app/views/projects/assignuser.html.erb
<h1>users List</h1>
<%= select_tag "users", options_from_collection_for_select(User.all, "id", "title") %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<%= link_to "BUG TRACKING SYSTEM", '/welcome' %>
<% @projects.each do |project| %>
<a href="/projects/<%= project.id%>">
<%= project.title %><br>


<% end %>
<%if current_user.user_type == "manager"%>
<%= link_to 'createproject', new_project_path %><br><br>
<% end %>
<br>
<%= link_to 'back', welcome_path %><br><br><br><br>

app/views/projects/new.html.erb
<h1>Create new Project Here</h1>
    <div >
      <%= form_with(model: @project , url: 'new_project_path' , method: :get) do |f| %>
        <h1>Bug Tracking System </h1>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br><br><br>
      <%= f.submit "createproject", class: "btn btn-primary"%><br><br>

    </div>
    <!--... -->
<% end %>

app/views/projects/show.html.erb
<%= link_to "BUG TRACKING SYSTEM", '/welcome' %>
<h1>Show Specific Projects</h1><br><br>
<%= link_to 'back', projects_path %><br><br><br><br>
<p>Project Title: <%= @project.title %></p><br><br>
<%if current_user.id == @project.user_id%>
<%= button_to "Delete", project_path(@project), method: :delete,data: { confirm: "Are you sure?" } %><br><br>
<%= link_to 'editproject', edit_project_path(@project) %><br><br>
<%end%>

<h2>User Assign</h2>
<% if @project_username.present?%>
<%@project_username.each do |p|%>
   <b>User Id:    </b><%= p.id %>&nbsp;&nbsp;
   <b>name:    </b><%= p.name %>&nbsp;&nbsp;
   <b>User Type:</b>    <%= p.user_type %>&nbsp;&nbsp;
<%if current_user.id == @project.user_id%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   <%= link_to "Remove User", remove_user_project_path(:project_id => @project.id,:user_id => p.id) %>
   <%end%>
    <%end%>
<%else%>
    <p>No users assigned to project</p>
<%end%>
<div>
<%if current_user.id == @project.user_id%>
<h4><%= link_to "Assign User", new_project_user_path(:project_id => @project.id)%></h4>

<%end%>

<h1>Show Specific Bug</h1><br><br>
<% @project.bugs.each do |bug| %>
  <p>
    <strong>Bug Title:</strong>
    <a href="/bugs/<%= bug.id%>">
      <%= bug.descriptive_title %>
  </p>
<% end %>
<%if current_user.user_type == 'qa'%>
<%= link_to'reportbug', new_bug_path(:project_id => @project.id) %><br><br>
<% end %>