config/routes.rb
Rails.application.routes.draw do

   root "sessions#new"

     resources :projects do
    member do
      patch 'assign_user'
      get 'remove_user'
      patch 'remove_user'
    end
  end



  resources :bugs do
    member do
      patch 'assign'
      put 'assign'
      patch 'change_status'
      put 'change_status'
    end
  end

  resources :project_users

   get '/signup', to: 'users#new'
   post '/signup', to: 'users#create'
   get '/login', to: 'sessions#new'
   post '/login', to: 'sessions#create'
   get '/welcome', to: 'sessions#welcome'
   #get '/authorized', to: 'sessions#page_requires_login'
   delete '/logout', to: 'sessions#destroy'
   #get '/projects', to: 'projects#index'
   #get '/projects/new', to: 'projects#new'
   #get '/projects/create' to: 'projects#new'
   #post '/projects/create' to: 'projects#create'
     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bug.rb
class Bug < ApplicationRecord
belongs_to :project
validates_uniqueness_of :descriptive_title, scope: :project_id
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController

  def index
    @bugs=Bug.where(assign_to:current_user.id)
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def new
    @bug = Bug.new
    @project_id = params[:project_id]
  end

  def create
    @bug = Bug.new(bug_params)
    if @bug.save
      redirect_to projects_path
    else
      render new_bug_path
    end
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    redirect_to projects_path
  end
 def assign
      @bug = Bug.find(params[:id])
    if @bug.update_attribute(:assign_to,current_user.id)
        @bug.update_attribute(:status,"started")
      redirect_to '/welcome'
    else
      redirect_to @bug , notice: "Not Assigned"
    end
  end
  def change_status
    @bug = Bug.find(params[:id])
    if @bug.update_attribute(:status,"resolved")
      redirect_to '/welcome'
    else
      redirect_to @bug , notice: "Not Assigned"
    end

  end

  private



  def bug_params
    params.require(:bug).permit(:descriptive_title,:deadline,:bug_type,:status,:screen_shot, :creator_id,:assign_to, :screenshot, :project_id)
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
  def data_for_view(all_bugs)
    bugs      = all_bugs.where(bug_type:'bug')
    features  = all_bugs.where(bug_type:'feature')

    view_data = {
    :features           => features,
    :total_features     => features.count,
    :new_features       => features.where(status:'new').count,
    :started_features   => features.where(status:'started').count,
    :completed_features => features.where(status:'completed').count,
    :bugs               => bugs,
    :total_bugs         => bugs.count,
    :new_bugs           => bugs.where(status:'new').count,
    :started_bugs       => bugs.where(status:'started').count,
    :resolved_bugs      => bugs.where(status:'resolved').count
    }

  end
end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f| %>
    <%=f.label :descriptive_title,'Title: ', :class=>"col-form-label col-md-1" %>
    <%=f.text_field :descriptive_title , :class => 'col-md-11 form-control' %><br><br>

    <%= f.label :deadline, 'Deadline:', :class=>"col-form-label col-md-1" %>
    <%= f.text_field :deadline, :class => 'form-control col-md-5' %><br><br>

    <%= label :bug_type, 'Type: ', :class=>" col-form-label col-md-1" %>
    <div class="form-control col-md-5",onchange(function)>
      <%= f.radio_button :bug_type, 'Bug' %>
      <%= label :bug_type, 'Bug' %>
      <%= f.radio_button :bug_type, 'feature' %>
      <%= label :bug_type, 'feature' %>
      </div>
      <% status = ['new', 'started', 'resolved'] %>
      <%= f.label :status, 'Status:', :class=>"col-form-label col-md-1"  %>
      <%= f.select(:status, status,{}, {:class => "form-control col-md-5",:required=>true}) %><br><br>
       <%= f.hidden_field :creator_id, value: current_user.id  %>
       <%= f.hidden_field :assign_to, value: nil%>

    <%= f.label :screenshot,'Screen shot:', :class=>"col-form-label" %>
    <%= f.file_field :screenshot, :class => "form-control",:accept => "image/x-png,image/gif" %><br><br>
      <%= f.label :project_id,'Project Id:', :class=>"col-form-label" %>
      <%= f.text_field :project_id, value: @project_id %><br><br><br>
    <%= f.submit  :class => 'btn btn-primary'%>
<%end%>

<script type="text/javascript">
  $(document).ready(function(){
    $('#deadline').datepicker({
      dateFormat: 'dd-mm-yyyy'
    });
  });
 $("input[name='bug[bug_type]']").change(function() {
    var obj = $("select[name='bug[status]']")[0][3]
    if(this.value==='bug'){
      obj.value = "resolved"
      obj.text  = "resolved"
    }
    else{
      obj.value = "completed"
      obj.text = "completed"
    }
  })
</script>

app/views/bugs/assign.html.erb
<h1>Bugs</h1>

app/views/bugs/edit.html.erb
<h1>edit status Bug</h1>

<%= form_for :bug , url: bug_path(@bug) do |f| %>
    <%=f.label :descriptive_title,'Title: ', :class=>"col-form-label col-md-1" %>
    <%=f.text_field :descriptive_title , :class => 'col-md-11 form-control' %><br><br>

    <%= f.label :deadline, 'Deadline:', :class=>"col-form-label col-md-1" %>
    <%= f.text_field :deadline, :class => 'form-control col-md-5' %><br><br>

    <%= label :bug_type, 'Type: ', :class=>" col-form-label col-md-1" %>
      <%= f.radio_button :bug_type, 'Bug' %>
      <%= label :bug_type, 'Bug' %>
      <%= f.radio_button :bug_type, 'feature' %>
      <%= label :bug_type, 'feature' %>
      <% status = ['new', 'started', 'resolved'] %>
      <%= f.label :status, 'Status:', :class=>"col-form-label col-md-1"  %>
      <%= f.select(:status, status,{}, {:class => "form-control col-md-5",:required=>true}) %><br><br>

    <%=f.label :screenshot,'Screen shot:', :class=>"col-form-label" %>
    <%=f.file_field :screenshot, :class => "form-control",:accept => "image/x-png,image/gif" %><br><br>
      <%=f.label :project_id,'Project Id:', :class=>"col-form-label" %>
      <%= f.text_field :project_id %><br><br><br>
    <%= f.submit  :class => 'btn btn-primary'%>
<%end%>

<script type="text/javascript">
  $(document).ready(function(){
    $('#deadline').datepicker({
      dateFormat: 'dd-mm-yyyy'
    });
  });
 $("input[name='bug[type]']").change(function() {
    var obj = $("select[name='bug[status]']")[0][2]
    if(this.value==='bug'){
      obj.value = "resolved"
      obj.text  = "resolved"
    }
    else{
      obj.value = "completed"
      obj.text = "completed"
    }
  })
</script>

app/views/bugs/index.html.erb
<% @bug.each do |bug| %>
<a href="/bugs/<%= bug.id%>">
<%= bug.descriptive_title %><br>
<% end %>
<%if current_user.user_type == 'qa'%>
<%= link_to'createbug', new_bug_path(@project_id) %><br><br>
<% end %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render "form", bug: @bug, project: @project %>

app/views/bugs/show.html.erb
<h1>Show Specific Bug</h1><br><br>

<h2>
<b>Bug ID</b>   : <%=@bug.id%><br>
<b>Bug Title</b> : <%=@bug.descriptive_title%><br>
<b>Bug Type</b>   : <%=@bug.bug_type%><br>
<b>Bug Status</b>   : <%=@bug.status%><br></h2>
  <%if current_user.user_type == 'qa'%>
  <%= button_to "Delete", bug_path( @bug), :method => :delete %>
  <%end%>
  <%if current_user.user_type == 'developer'%>
 <%= button_to "assign", assign_bug_path(:id=> @bug.id), :method => :put %> <br>
<%if current_user.id == @bug.assign_to%>
  <%= button_to "Change status to resolved ", change_status_bug_path(:id=> @bug.id), :method => :put %>
  <%end%>
  <%end%>